version: '3'
services:

  monitor-server:
    image: cppla/serverstatus:arm
    container_name: monitor-server
    restart: always
    volumes:
      - "./config.json:/ServerStatus/server/config.json"
    ports:
#     - "35601:35601"
      - "80:80"

  monitor-client:
    build: ./client
    container_name: monitor-client
    restart: always
    command: USER=paicoop.net
    #network_mode: "host"
    depends_on:
      - monitor-server
